// Generated cross-validation reference values; pedantic lints are noisy here.
#![allow(clippy::pedantic)]

//! Tests for `umap_rs::sparse_metrics`, ported from the sparse parts of
//! `umap/umap/tests/test_umap_metrics.py` plus Python-generated reference
//! values.
//!
//! Reference values were generated with umap-learn 0.5.12
//! (`/tmp/opencode/umap-py/bin/python`, which imports `umap.sparse` and runs
//! the numba kernels) by a throwaway script kept outside the repo at
//! `/tmp/opencode/gen_sparse_refs.py`, on exactly the fixed inputs below.
//! Dense-oracle values were computed with scipy on the dense versions of the
//! same vectors (`crate::distances::named_distances` did not exist yet at
//! porting time).
//!
//! # Reference inputs
//!
//! - Binary 0/1 vectors over 10 features: `B0`, `B1`, `B2`, `B_EMPTY`
//! - Float vectors: `F0`, `F1`, `F2`, `F_EMPTY`
//! - Hellinger inputs (abs of F0/F1): `H0`, `H1`
//! - `ll_dirichlet` inputs (abs of F0/F1 plus 0.25): `P0`, `P1`
//! - A small 3x5 CSR pair plus the union sparsity for the sset kernels

#![allow(clippy::unreadable_literal)] // generated reference constants
#![allow(clippy::float_cmp)] // exact f32 constants generated by numba

use approx::assert_relative_eq;
use umap_rs::csr::{CooMatrix, CsrMatrix};
use umap_rs::sparse_metrics::{
    arr_intersect, arr_union, general_sset_intersection, general_sset_union, norm,
    sparse_named_distances, sparse_special_metric_names, SparseMetricFn,
};

// Binary 0/1 vectors over 10 features.
const B0: (&[i32], &[f32]) = (&[0, 2, 4, 7], &[1.0, 1.0, 1.0, 1.0]);
const B1: (&[i32], &[f32]) = (&[2, 4, 5, 9], &[1.0, 1.0, 1.0, 1.0]);
const B2: (&[i32], &[f32]) = (&[1, 3, 6, 8], &[1.0, 1.0, 1.0, 1.0]);
const B_EMPTY: (&[i32], &[f32]) = (&[], &[]);

// Float vectors.
const F0: (&[i32], &[f32]) = (&[0, 1, 3, 5, 8], &[0.5, -1.25, 2.0, 3.5, 0.75]);
const F1: (&[i32], &[f32]) = (&[1, 2, 3, 6, 8, 9], &[1.5, 0.25, -0.5, 2.25, 1.0, 0.5]);
const F2: (&[i32], &[f32]) = (&[4, 7], &[1.0, 2.0]);
const F_EMPTY: (&[i32], &[f32]) = (&[], &[]);

// Hellinger inputs: abs of F0/F1 (as in the Python test suite).
const H0: (&[i32], &[f32]) = (&[0, 1, 3, 5, 8], &[0.5, 1.25, 2.0, 3.5, 0.75]);
const H1: (&[i32], &[f32]) = (&[1, 2, 3, 6, 8, 9], &[1.5, 0.25, 0.5, 2.25, 1.0, 0.5]);

// ll_dirichlet inputs: abs of F0/F1 plus 0.25 (positive data).
const P0: (&[i32], &[f32]) = (&[0, 1, 3, 5, 8], &[0.75, 1.5, 2.25, 3.75, 1.0]);
const P1: (&[i32], &[f32]) = (&[1, 2, 3, 6, 8, 9], &[1.75, 0.5, 0.75, 2.5, 1.25, 0.75]);
const P2: (&[i32], &[f32]) = (&[4, 7], &[1.25, 2.25]);

// Reference values generated from umap-learn 0.5.12 numba kernels.
const SPATIAL_EXPECTED: [[f64; 6]; 4] = [
    // (F0, F1): euclidean, manhattan, chebyshev, canberra, braycurtis, cosine
    [
        5.634713834792322,
        12.5,
        3.5,
        7.142857074737549,
        1.1904761791229248,
        1.1652824009034168,
    ],
    // (F1, F2)
    [3.724916106437835, 9.0, 2.25, 8.0, 1.0, 1.0],
    // (F0, F_EMPTY)
    [4.315669125408017, 8.0, 3.5, 5.0, 1.0, 1.0],
    // (F_EMPTY, F_EMPTY)
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
];

const MINKOWSKI_P3_EXPECTED: [f64; 4] = [
    4.497426512077409,  // (F0, F1)
    2.9252355716473883, // (F1, F2)
    3.7651241062259087, // (F0, F_EMPTY)
    0.0,                // (F_EMPTY, F_EMPTY)
];

const CORRELATION_EXPECTED: [f64; 4] = [
    1.488846177772798, // (F0, F1)
    1.293399410443569, // (F1, F2)
    1.0,               // (F0, F_EMPTY)
    0.0,               // (F_EMPTY, F_EMPTY)
];

const HELLINGER_EXPECTED: [f64; 4] = [
    0.730082231937693, // (H0, H1)
    1.0,               // (H1, H2=F2)
    1.0,               // (H0, H_EMPTY)
    0.0,               // (H_EMPTY, H_EMPTY)
];

const LL_DIRICHLET_EXPECTED: [f64; 4] = [
    0.8327104735158295, // (P0, P1)
    1.0897166635787163, // (P1, P2)
    100_000_000.0,      // (P0, P_EMPTY) — n1 == 0 or n2 == 0 sentinel
    0.0,                // (P_EMPTY, P_EMPTY)
];

// Binary metrics with (rows: hamming, matching, kulsinski, rogerstanimoto,
// russellrao, sokalmichener) — all require n_features = 10.
const BINARY_NF_EXPECTED: [[f64; 6]; 4] = [
    // (B0, B1)
    [
        0.4,
        0.4,
        0.8571428571428571,
        0.5714285714285714,
        0.8,
        0.5714285714285714,
    ],
    // (B0, B2)
    [0.8, 0.8, 1.0, 0.8888888888888888, 1.0, 0.8888888888888888],
    // (B0, B_EMPTY)
    [0.4, 0.4, 1.0, 0.5714285714285714, 1.0, 0.5714285714285714],
    // (B_EMPTY, B_EMPTY)
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
];

// Binary metrics without n_features (jaccard, dice, sokalsneath).
const BINARY_EXPECTED: [[f64; 3]; 4] = [
    // (B0, B1)
    [0.6666666666666666, 0.5, 0.8],
    // (B0, B2)
    [1.0, 1.0, 1.0],
    // (B0, B_EMPTY)
    [1.0, 1.0, 1.0],
    // (B_EMPTY, B_EMPTY)
    [0.0, 0.0, 0.0],
];

// Python-generated sset references (see module docs). The result COO sparsity
// is the per-row union: rows [0,0,0,0,1,1,1,1,2,2], cols [0,1,2,4,0,1,2,3,2,4].
const SSET_ROWS: &[i32] = &[0, 0, 0, 0, 1, 1, 1, 1, 2, 2];
const SSET_COLS: &[i32] = &[0, 1, 2, 4, 0, 1, 2, 3, 2, 4];
const INTERSECT_MW05: [f64; 10] = [
    9.999999747378752e-06,
    0.020000001415610313,
    0.30000001192092896,
    8.999999408842996e-05,
    0.010000000707805157,
    3.000000106112566e-05,
    0.04000000283122063,
    0.3499999940395355,
    0.015000000596046448,
    0.03500000014901161,
];
const INTERSECT_MW03: [f64; 10] = [
    0.0019306977046653628,
    0.03376169875264168,
    0.40169087052345276,
    0.017376279458403587,
    0.02508484572172165,
    0.005792093463242054,
    0.04543987661600113,
    0.5200979709625244,
    0.029845518991351128,
    0.04291246458888054,
];
const INTERSECT_MW05_COMPLEMENT: [f64; 10] = [
    9.999999747378752e-06,
    0.029999999329447746,
    0.19999998807907104,
    8.999999408842996e-05,
    0.03999999910593033,
    3.000000106112566e-05,
    0.009999999776482582,
    0.3499999940395355,
    0.03500000014901161,
    0.015000000596046448,
];
const UNION_EXPECTED: [f64; 10] = [
    0.1899999976158142,
    0.4300000071525574,
    0.800000011920929,
    0.9099999666213989,
    0.24000000953674316,
    0.3700000047683716,
    0.8100000023841858,
    0.8500000238418579,
    0.33500000834465027,
    0.7149999737739563,
];

/// Resolve a named sparse metric and call it.
fn call(metric: &str, a: (&[i32], &[f32]), b: (&[i32], &[f32]), kwds: &[f32]) -> f32 {
    sparse_named_distances(metric).unwrap_or_else(|| panic!("unknown sparse metric: {metric}"))(
        a.0, a.1, b.0, b.1, kwds,
    )
}

/// Compare against a Python-generated f64 reference with f32 tolerance.
fn assert_close(actual: f32, expected: f64) {
    assert_relative_eq!(actual, expected as f32, epsilon = 1e-6, max_relative = 1e-5);
}

/// The small CSR pair used by the sset kernel tests, plus the result COO
/// (pre-filled with zeros on the union sparsity).
fn sset_inputs() -> (CsrMatrix, CsrMatrix, CooMatrix) {
    let left = CsrMatrix {
        shape: (3, 5),
        indptr: vec![0, 3, 5, 5], // row 2 is empty
        indices: vec![0, 2, 4, 1, 3],
        data: vec![0.1, 0.5, 0.9, 0.3, 0.7],
    };
    let right = CsrMatrix {
        shape: (3, 5),
        indptr: vec![0, 2, 5, 7],
        indices: vec![1, 2, 0, 2, 3, 2, 4],
        data: vec![0.4, 0.6, 0.2, 0.8, 0.5, 0.3, 0.7],
    };
    let result = CooMatrix {
        shape: (3, 5),
        row: SSET_ROWS.to_vec(),
        col: SSET_COLS.to_vec(),
        data: vec![0.0; 10],
    };
    (left, right, result)
}

// ---------------------------
// Sparse set operation tests
// ---------------------------

#[test]
fn test_arr_union_copies_nonempty_input() {
    // Python: test_arr_union_copies_nonempty_input
    let indices = [0, 2];
    assert_eq!(arr_union(&[], &indices), vec![0, 2]);
    assert_eq!(arr_union(&indices, &[]), vec![0, 2]);
    // union sorts and dedups
    assert_eq!(arr_union(&[3, 1], &[2, 1]), vec![1, 2, 3]);
}

#[test]
fn test_arr_intersect() {
    assert_eq!(arr_intersect(&[0, 2], &[0, 2]), vec![0, 2]);
    assert_eq!(arr_intersect(&[0, 2], &[1, 3]), Vec::<i32>::new());
    // Python's simplified intersect keeps one entry per adjacent equal pair
    // in the sorted concatenation (multiset-like semantics), unlike
    // numpy.intersect1d which dedups first.
    assert_eq!(arr_intersect(&[0, 0, 2], &[0, 2, 2]), vec![0, 0, 2, 2]);
}

// ---------------------------
// Sparse spatial metric tests
// ---------------------------

#[test]
fn test_sparse_spatial_metrics_reference_values() {
    let cases = [(F0, F1), (F1, F2), (F0, F_EMPTY), (F_EMPTY, F_EMPTY)];
    let metrics = [
        "euclidean",
        "manhattan",
        "chebyshev",
        "canberra",
        "braycurtis",
        "cosine",
    ];
    for ((a, b), expected) in cases.iter().zip(&SPATIAL_EXPECTED) {
        for (metric, expected_value) in metrics.iter().zip(expected) {
            assert_close(call(metric, *a, *b, &[]), *expected_value);
        }
    }
}

#[test]
fn test_sparse_minkowski_reference_values() {
    let cases = [(F0, F1), (F1, F2), (F0, F_EMPTY), (F_EMPTY, F_EMPTY)];
    for ((a, b), expected) in cases.iter().zip(&MINKOWSKI_P3_EXPECTED) {
        assert_close(call("minkowski", *a, *b, &[3.0]), *expected);
    }
    // default p = 2.0 when no extra args are passed
    assert_close(call("minkowski", F0, F_EMPTY, &[]), 4.315669125408017);
}

#[test]
fn test_sparse_correlation_reference_values() {
    let cases = [(F0, F1), (F1, F2), (F0, F_EMPTY), (F_EMPTY, F_EMPTY)];
    for ((a, b), expected) in cases.iter().zip(&CORRELATION_EXPECTED) {
        assert_close(call("correlation", *a, *b, &[10.0]), *expected);
    }
}

#[test]
fn test_sparse_hellinger_reference_values() {
    let cases = [(H0, H1), (H1, F2), (H0, F_EMPTY), (F_EMPTY, F_EMPTY)];
    for ((a, b), expected) in cases.iter().zip(&HELLINGER_EXPECTED) {
        assert_close(call("hellinger", *a, *b, &[]), *expected);
    }
}

#[test]
fn test_sparse_ll_dirichlet_reference_values() {
    let cases = [(P0, P1), (P1, P2), (P0, F_EMPTY), (F_EMPTY, F_EMPTY)];
    for ((a, b), expected) in cases.iter().zip(&LL_DIRICHLET_EXPECTED) {
        assert_close(call("ll_dirichlet", *a, *b, &[]), *expected);
    }
}

// ---------------------------
// Sparse binary metric tests
// ---------------------------

#[test]
fn test_sparse_binary_metrics_reference_values() {
    let cases = [(B0, B1), (B0, B2), (B0, B_EMPTY), (B_EMPTY, B_EMPTY)];
    let nf_metrics = [
        "hamming",
        "matching",
        "kulsinski",
        "rogerstanimoto",
        "russellrao",
        "sokalmichener",
    ];
    let plain_metrics = ["jaccard", "dice", "sokalsneath"];
    for (case_index, ((a, b), expected_nf)) in cases.iter().zip(&BINARY_NF_EXPECTED).enumerate() {
        for (metric, expected) in nf_metrics.iter().zip(expected_nf) {
            assert_close(call(metric, *a, *b, &[10.0]), *expected);
        }
        for (metric, expected) in plain_metrics.iter().zip(&BINARY_EXPECTED[case_index]) {
            assert_close(call(metric, *a, *b, &[]), *expected);
        }
    }
}

// ---------------------------
// Name resolution / contract tests
// ---------------------------

#[test]
fn test_sparse_metric_fn_type_contract() {
    // the type alias is the crate-wide contract for sparse metrics
    let f: SparseMetricFn = sparse_named_distances("jaccard").unwrap();
    assert_close(f(B0.0, B0.1, B1.0, B1.1, &[]), 0.6666666666666666);
}

#[test]
fn test_unknown_names_return_none() {
    for name in ["sqeuclidean", "l2", "yule", "categorical", "bogus", ""] {
        assert!(sparse_named_distances(name).is_none(), "name: {name}");
    }
}

#[test]
fn test_metric_aliases() {
    let aliases = [
        ("l1", "manhattan"),
        ("taxicab", "manhattan"),
        ("linf", "chebyshev"),
        ("linfty", "chebyshev"),
        ("linfinity", "chebyshev"),
    ];
    for (alias, canonical) in aliases {
        assert!(sparse_named_distances(alias).is_some(), "alias: {alias}");
        // aliases resolve to the same behaviour as their canonical metric
        assert_eq!(
            call(alias, F0, F1, &[]),
            call(canonical, F0, F1, &[]),
            "alias: {alias}"
        );
    }
    // aliases resolve to distinct behaviour per family
    assert_close(call("l1", F0, F1, &[]), 12.5);
    assert_close(call("linf", F0, F1, &[]), 3.5);
}

#[test]
fn test_special_metric_names() {
    // Python: SPARSE_SPECIAL_METRICS = {hellinger, ll_dirichlet}
    assert_eq!(
        sparse_special_metric_names(),
        &["hellinger", "ll_dirichlet"]
    );
}

#[test]
fn test_norm() {
    assert_eq!(norm(&[0, 1, 3], &[3.0, 4.0, 0.0]), 5.0);
    assert_eq!(norm(&[], &[]), 0.0);
}

#[test]
fn test_sparse_euclidean_accepts_empty_inputs() {
    // Python: test_sparse_euclidean_accepts_arrays_captured_by_custom_metric
    let captured = (&[0, 2][..], &[0.0f32, 2.0][..]);
    let empty = (&[][..], &[][..]);
    assert_eq!(
        call("euclidean", captured, empty, &[]),
        2.0,
        "zero entries are dropped by sparse_sum"
    );
    assert_eq!(call("euclidean", empty, captured, &[]), 2.0);
}

// ---------------------------
// Sset kernel tests
// ---------------------------

#[test]
fn test_general_sset_intersection_reference_mw05() {
    let (left, right, mut result) = sset_inputs();
    general_sset_intersection(
        &left.indptr,
        &left.indices,
        &left.data,
        &right.indptr,
        &right.indices,
        &right.data,
        &result.row,
        &result.col,
        &mut result.data,
        0.5,
        false,
    );
    for (actual, expected) in result.data.iter().zip(&INTERSECT_MW05) {
        assert_close(*actual, *expected);
    }
}

#[test]
fn test_general_sset_intersection_reference_mw03() {
    let (left, right, mut result) = sset_inputs();
    general_sset_intersection(
        &left.indptr,
        &left.indices,
        &left.data,
        &right.indptr,
        &right.indices,
        &right.data,
        &result.row,
        &result.col,
        &mut result.data,
        0.3,
        false,
    );
    for (actual, expected) in result.data.iter().zip(&INTERSECT_MW03) {
        assert_close(*actual, *expected);
    }
}

#[test]
fn test_general_sset_intersection_right_complement() {
    let (left, right, mut result) = sset_inputs();
    general_sset_intersection(
        &left.indptr,
        &left.indices,
        &left.data,
        &right.indptr,
        &right.indices,
        &right.data,
        &result.row,
        &result.col,
        &mut result.data,
        0.5,
        true,
    );
    for (actual, expected) in result.data.iter().zip(&INTERSECT_MW05_COMPLEMENT) {
        assert_close(*actual, *expected);
    }
}

#[test]
fn test_general_sset_union_reference() {
    let (left, right, mut result) = sset_inputs();
    general_sset_union(
        &left.indptr,
        &left.indices,
        &left.data,
        &right.indptr,
        &right.indices,
        &right.data,
        &result.row,
        &result.col,
        &mut result.data,
    );
    for (actual, expected) in result.data.iter().zip(&UNION_EXPECTED) {
        assert_close(*actual, *expected);
    }
}

#[test]
fn test_general_sset_intersection_leaves_unmatched_entries() {
    // Entries absent from both left and right rows keep their pre-filled
    // value (the numba kernel only overwrites where the mixing condition
    // holds).
    let left = CsrMatrix {
        shape: (1, 4),
        indptr: vec![0, 2],
        indices: vec![0, 1],
        data: vec![0.5, 0.7],
    };
    let right = CsrMatrix {
        shape: (1, 4),
        indptr: vec![0, 2],
        indices: vec![0, 1],
        data: vec![0.2, 0.9],
    };
    let mut data = [7.0f32, 7.0];
    general_sset_intersection(
        &left.indptr,
        &left.indices,
        &left.data,
        &right.indptr,
        &right.indices,
        &right.data,
        &[0, 0],
        &[2, 3],
        &mut data,
        0.5,
        false,
    );
    assert_eq!(data, [7.0, 7.0]);
}

#[test]
fn test_general_sset_robust_to_out_of_range_row() {
    // Python would raise IndexError for a result row beyond indptr; the Rust
    // kernel must not panic (it simply leaves the entry untouched).
    let left = CsrMatrix {
        shape: (1, 4),
        indptr: vec![0, 2],
        indices: vec![0, 1],
        data: vec![0.5, 0.7],
    };
    let right = CsrMatrix {
        shape: (1, 4),
        indptr: vec![0, 2],
        indices: vec![0, 1],
        data: vec![0.2, 0.9],
    };
    let mut data = [7.0f32, 7.0];
    general_sset_intersection(
        &left.indptr,
        &left.indices,
        &left.data,
        &right.indptr,
        &right.indices,
        &right.data,
        &[5, 5],
        &[2, 3],
        &mut data,
        0.5,
        false,
    );
    general_sset_union(
        &left.indptr,
        &left.indices,
        &left.data,
        &right.indptr,
        &right.indices,
        &right.data,
        &[5, 5],
        &[2, 3],
        &mut data,
    );
    // intersection leaves the entry untouched; union unconditionally writes
    // (like Python), falling back to the minimum floors:
    // 0.25 + 0.1 - 0.25 * 0.1 = 0.325
    assert_eq!(data, [0.325, 0.325]);
}

// ---------------------------
// Dense oracle cross-checks
// ---------------------------

#[test]
fn test_sparse_matches_dense_oracle() {
    // scipy values on the dense versions of the same vectors (crate::distances
    // not available at porting time — see module docs).
    assert_close(call("euclidean", F0, F1, &[]), 5.634713834792322);
    assert_close(call("cosine", F0, F1, &[]), 1.1652824009034166);
    assert_close(call("cosine", B0, B1, &[]), 0.5);
    assert_close(call("hamming", B0, B1, &[10.0]), 0.4);
    assert_close(call("jaccard", B0, B1, &[]), 0.6666666666666666);
    assert_close(call("dice", B0, B1, &[]), 0.5);
}
